[package]
name = "proj"
description = "High-level Rust bindings for the latest stable version of PROJ"
version = "0.20.5"
authors = [
    "The Georust Developers <mods@georust.org>"
]
repository = "https://github.com/georust/proj"
documentation = "https://docs.rs/proj/"
keywords = ["proj", "projection", "osgeo", "geo"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
proj-sys = { version = "0.18.3", path = "proj-sys" }
geo-types = { version = "0.6", optional = true }
libc = "0.2.62"
num-traits = "0.2.8"
thiserror = "1.0.4"
reqwest = { version = "0.10.6", optional = true, default-features = false, features = ["blocking", "rustls-tls"] }

[workspace]
members = ["proj-sys"]

[features]
bundled_proj = [ "proj-sys/bundled_proj" ]
pkg_config = [ "proj-sys/pkg_config" ]
network = ["reqwest"]

[dev-dependencies]
assert_approx_eq = "1.1.0"

[package.metadata.docs.rs]
features = [ "proj-sys/nobuild", "network", "geo-types" ]
rustdoc-args = ["--cfg", "docsrs"]
